<?php

/**
 * @file
 * LandofOpportunity content filter module.
 * This module creates additional content tabs for different content type.
 * User can choose content type on admin setting page admin/config/content/node_order.
 */

/**
 * Implements hook_menu().
 * Creates menu link for content filters tabs and admin settings page.
 * 
 * @return array
 */
function landofopp_cms_content_filter_menu() {
  
  $order_types = landofopp_cms_content_filter_get_types();
  // add filter pages for special content types
  $types = node_type_get_types();
  if (!empty($order_types)) {
    $key = 0;
    foreach ($order_types as $type => $title) {
      $key++;
      $items['admin/content/' . $type] = array(
        'title' => $title,
        'description' => "View, edit, and delete " . $title . " content.",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('landofopp_cms_content_filter_content_by_type', 2),
        'access arguments' => array('administer nodes'),
        'file' => 'landofopp_cms_content_filter.admin.inc',
        'weight' => '-' . $key,
        'type' => MENU_LOCAL_TASK,
      );
    }  
  }
  // admin settings page
  $items['admin/config/content/node_order'] = array(
    'title' => 'Content filter setting',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('landofopp_cms_content_filter_setting_form'),
    'access arguments' => array('administer nodes'),
    'file' => 'landofopp_cms_content_filter.admin.inc',
  );
  return $items;
}

/**
 * Return list of content type, which user choose in admin settings page
 * 
 * @return array
*/

function landofopp_cms_content_filter_get_types() {
  $options = array();
  // get all content type
  $types = node_type_get_types();
  $order_types = variable_get('content_filter_types', array());
  if (!empty($order_types)) {
    foreach ($order_types as $type => $val) {
      if (empty($types[$type]->name)) continue;
      $title = $types[$type]->name;
      if ($type == 'rich_media') $title .= 's';
      if ($type == 'subpage') $title = 'Pages';
      if ($type == 'category') $title = 'Categories';
      if ($val) $options[$type] = $title;
    }
    unset($options['subpage']);
    $result = array('subpage' => 'Pages') + $options;
    $options = $result;
  }
  return $options;
}
